### ISSUE TITLE
help use

### ISSUE THREAD

**Issue by nagarou-fr** [RebeccaStevens/uMod-Plugin-UiBuilderLibrary#2]
Good morning,
I tested the plugin and I can't understand how to add a label for example

```cs
MyUi = new UI("Overlay", (mainPanel,player) =>
{
  mainPanel.CursorEnabled = true;
  mainPanel.Image.Color = "1 1 1 0.5";
  mainPanel.Bounds.MinX = 0.1;
  mainPanel.Bounds.MaxX = 0.9;
  mainPanel.Bounds.MinY = 0.2;
  mainPanel.Bounds.MaxY = 0.8;
      
  mainPanel.AddLabel((label) => {
    label.Text = "test"; 
  });
```

//error Error while compiling te: A readonly field cannot be assigned to (except in a constructor or init-only setter of the type in which the field is defined or a variable initializer) | Line: 30, Pos: 21

**Comment by nagarou-fr** [comment]
Error while compiling te: Property or indexer 'UiBuilderLibrary.LabelElement.Instance.Text' cannot be assigned to -- it is read only | Line: 29, Pos: 9

**Comment by RebeccaStevens** [comment]
You'll want to use `label.Text.Text = "test"` instead of `label.Text = "test"`.

Here's a more full example:

```cs
mainPanel.AddLabel((label) =>
{
  label.Text.Text = "test";
  label.Text.Align = TextAnchor.LowerCenter;
  label.Text.FontSize = 65;
  label.Text.Color = ".9 .5 .1 1";
  label.Bounds.MinX = 0;
  label.Bounds.MinY = 0;
  label.Bounds.MaxX = 1;
  label.Bounds.MaxY = 1;

  return false;
});
```

**Comment by nagarou-fr** [comment]
thank you it works I have another question

I am making a grid and how I can return the cell id or Rows Columns position in the following example the label is always equal to 22 and I would like each cell to be a distinct id

and if possible to have a complete example of AddTabs because I don't understand in which case to use it

Thank you for your help

```cs
subPanel2.AddGrid((grid) =>
{
grid.Rows = 2;
grid.Columns = 11;
grid.Bounds.MinX = 0;
grid.Bounds.MaxX = 1;
grid.Bounds.MinY = 0;
grid.Bounds.MaxY = 1;
for (var i = 0; i < grid.Rows * grid.Columns; i++)
{
    grid.AddCell((cell) =>
    {
        
        cell.AddLabel((label) =>
        {
            label.Text.Text = i; // all return 22
            label.Text.FontSize = 28;
            label.Text.Color = "0.27 0.33 0.42 1.00";
            return true;
        });
        return true;
    });
}

```

**Comment by RebeccaStevens** [comment]
So this issue is caused by there only being a single reference to the variable `i`, and by the time the callback of adding a label is called, the `for` loop has already finished, thus `i` is at its max value.

To solve this, each iteration of the loop needs its own variable to store the current iteration number in so each callback call is only referencing the variable for its iteration in the loop.

```cs
for (var i = 0; i < grid.Rows * grid.Columns; i++)
{
    var index = i; // Store a scoped value of i - use this var instead of i in the rest of loop.
}
```

**Comment by nagarou-fr** [comment]
great thank you it works and I have another question
and if possible have a complete example of AddTabs because I don't understand in which case to use it what element we can put there etc.
